name: Wordpress for Hosting
description: "Hosting stack for Wordpress hosting"
version: "v0.0.1-test"
category: CMS
maintainer: Hallgrimur Finnbogason <halli@halli.org>
license: MIT
projectURl: "https://github.com/hallzi/rancher-test"
